Import("env")

env.Program( "dis31", [
  "compat.c",
  "main.cpp",
  "readsdf.cpp",
  "dis31.cpp",
  "sr.cpp",
])

env.Program( "entertab", ["entertab.cpp", "compat.c"] )

env.Program( "d8031", ["d8031.cpp", "dis31.cpp", "compat.c"] )

env.Program( "d65c02", ["d65c02.c", "compat.c"] )